gsainfoteam/ziggle-fe

.eslintrc.json
src/App.tsx
src/atoms/button/Button.stories.tsx
src/atoms/containers/grid/Grid.tsx
src/atoms/figures/circle/Circle.stories.tsx
src/atoms/inputs/checkbox/Checkbox.stories.tsx
src/atoms/inputs/checkbox/Checkbox.tsx
src/atoms/inputs/input/Input.stories.tsx
src/atoms/text/Text.stories.tsx
src/layout/Layout.tsx
src/molecules/chip/Chip.stories.tsx
src/molecules/chip/Chip.tsx
src/molecules/d-day/DDay.stories.tsx
src/molecules/d-day/DDay.tsx
src/molecules/horizontalScrollButton/HorizontalScrollButton.stories.tsx
src/molecules/noticeTypeRadio/NoticeTypeRadio.stories.tsx
src/molecules/noticeTypeRadio/NoticeTypeRadio.tsx
src/molecules/search/Search.stories.tsx
src/molecules/tag/Tag.stories.tsx
src/molecules/tag/Tag.tsx
src/pages/home/HomePage.tsx
src/pages/playground/PlaygroundPage.tsx

resolve deprecated imports, unused imports

---

.storybook/main.ts
.storybook/preview.ts
package.json
src/App.tsx
src/apis/image/image-api.ts
src/atoms/button/Button.tsx
src/atoms/highlight/Highlight.tsx
src/atoms/text/Text.tsx
src/layout/Layout.tsx
src/molecules/pagination/Pagination.tsx
src/molecules/searchBar/SearchBar.tsx
src/pages/allNotices/AllNoticesPage.tsx
src/pages/searchPage/SearchPage.tsx
src/templates/navbar/Navbar.tsx
src/templates/searchResult/SearchResult.tsx
src/templates/searchResultText/SearchResultText.tsx
src/types/paths.ts
src/types/types.ts
src/utils/GetHighlightedText.tsx
vite.config.ts
yarn.lock

전체 공지 페이지 추가 및
- 각종 UI 버그 수정
- SearchPage 및 SearchResult, SearchResultText를 범용적으로 사용할 수 있도록 padding, margin, 계층 구조 등 변경
- SearchResult 리팩토링 (Text 중첩 문제 해결 등)

:sparkles: Add all notices page

---

src/App.tsx
src/apis/user/user-api.ts
src/pages/myPage/MypageProfile.tsx
src/templates/navbar/Navbar.tsx

:sparkles: Fixed All

---

package.json
src/atoms/highlight/Highlight.tsx
src/hooks/useAuth.tsx
src/layout/Layout.tsx
src/pages/myPage/MyPage.tsx
src/pages/noticeSections/RemindedNoticesPage.tsx
src/pages/noticeSections/WrittenNoticesPage.tsx
src/pages/noticeWriting/NoticeWritingPage.tsx
yarn.lock

:sparkles: Add login toast

---

src/templates/footer/Footer.tsx

feat: show preparing alert when click download app link

---

src/templates/footer/Footer.tsx

Reverts gsainfoteam/ziggle-fe#82

Revert "feat: show preparing alert when click download app link"

---

src/organisms/zabo/TextZabo.tsx

:bug: Fix textzabo condition bug

---

src/pages/noticeWriting/NoticeWritingPage.tsx

feat: add link, image, code support for editor

---

src/templates/zaboCarousel/ZaboCarousel.tsx
src/utils/date.ts

아마 고쳐졌을 거에요
@2paperstar 가 다 알려줌

:bug: Fix deadline bug and empty carousel bug

---

src/app/[lng]/page.tsx
src/app/[lng]/section/all/page.tsx

아니 메인 페이지는 다이나믹으로 렌더링해야 하는데 안 그렇더라고요? 그래서 공지가 새로 올라와도 원래는 새로운 글을 목록에서는 볼 수 없었는데 이제 볼 수 있게 바꿨어요 :)

fix: make list page dynamic

---

src/api/auth/auth.ts
src/app/components/templates/Navbar/Navbar.tsx

feat: show authentication info in navbar

---

.vscode/settings.json

code actions on save: fix all eslint, sort imports
disable format on save

chore: apply recommended vscode setting

---

src/app/[lng]/search/Result.tsx
src/app/[lng]/search/page.tsx
src/app/components/molecules/Pagination/Pagination.tsx

:sparkles: Pagination to search page

---

.vscode/settings.json
src/app/[lng]/layout.tsx
src/app/[lng]/mypage/MypageProfile.tsx
src/app/[lng]/mypage/MypageTable.tsx
src/app/[lng]/mypage/page.tsx
src/app/[lng]/notice/[id]/page.tsx
src/app/[lng]/page.tsx
src/app/[lng]/search/Result.tsx
src/app/[lng]/search/page.tsx
src/app/[lng]/section/all/layout.tsx
src/app/[lng]/section/all/page.tsx
src/app/[lng]/write/AttatchPhotoArea.tsx
src/app/[lng]/write/DeepLButton.tsx
src/app/[lng]/write/TagInput.tsx
src/app/[lng]/write/page.tsx
src/app/components/molecules/DDay/DDay.tsx
src/app/components/organisms/NoticeInfo/NoticeInfo.tsx
src/app/components/organisms/Zabo/Zabo.tsx
src/app/components/templates/Footer/Footer.tsx
src/app/components/templates/Navbar/Navbar.stories.tsx
src/app/components/templates/Navbar/Navbar.tsx
src/app/components/templates/ResultZabo/ResultZabo.tsx
src/app/i18next/client.ts
src/app/i18next/index.ts

`{ t: T }`를 대체하기 위한 `PropsWithT`, `{ lng: Locale }`을 대체하기 위한 `PropsWithLng`를 추가하였습니다

refactor: clean up type

---

src/api/notice/notice.ts
src/app/[lng]/search/Result.tsx
src/app/components/atoms/Analytics/Analytics.tsx
src/app/components/organisms/Zabo/TextZabo.tsx
src/app/components/templates/ResultZabo/ResultImageZabo.tsx
src/app/components/templates/ResultZabo/ResultTextZabo.tsx
src/app/components/templates/ResultZabo/ResultZabo.tsx

refactor: make result zabo component server component

---

src/app/[lng]/write/AttatchPhotoArea.tsx
src/app/[lng]/write/AttatchedPhoto.tsx
src/app/[lng]/write/page.tsx
src/app/components/organisms/ImageCarousel/ImageCarousel.tsx

3개 이상 올릴 때 안 보이는 문제, 이미지 비율 이상하게 보이는 문제

fix: image upload bug

---

src/app/components/molecules/ZaboImage/ZaboImage.tsx
src/app/components/templates/ResultZabo/ResultImageZabo.tsx

feat: result image zabo with border

---

.github/workflows/staging.yaml

마스터에 머지가 되면 [스테이징](https://stg.ziggle.gistory.me)에 배포가 되고, 깃허브 기능을 사용해서 release를 생성하면 [프로덕션](https://ziggle.gistory.me)에 배포되는 방식으로 변경하였습니다.

chore(ci/cd): separate production / staging pipeline

---

src/app/[lng]/search/page.tsx

fix: make order by recent in search page

---

.github/workflows/production.yaml
.github/workflows/staging.yaml
src/app/[lng]/layout.tsx

chore(ci/cd): use docker in production

---

global.d.ts
src/api/auth/auth.ts
src/api/notice/notice.ts
src/app/api/bff/[...ziggle]/route.ts
src/middleware.ts

feat: reaction with bff

---

src/app/components/templates/Navbar/SearchBar.tsx

fix: search bar event issue

---

.github/workflows/preview.yaml
.github/workflows/production.yaml
.github/workflows/staging.yaml

node 16 deprecated in actions runner

chore(ci/cd): use actions/checkout@v4 instead of v3

---

src/app/components/templates/Sidebar/sidebarObject.ts

fix: block group page

---

src/app/[lng]/(common)/(needSidebar)/[category]/CategorizedNotices.tsx
src/app/[lng]/(common)/(needSidebar)/[category]/page.tsx
src/app/components/molecules/Pagination/Pagination.tsx

with redirect page=0 if page value is invalid

fix: feed page blinking issue

---

.github/workflows/preview.yaml

chore(ci/cd): detach deployment action for preview pr

---

src/app/[lng]/(write)/write/NoticeEditor.tsx
src/app/[lng]/(write)/write/TitleAndContent.tsx

fix: draft preserved even if notice is uploaded

---

.storybook/preview.tsx
package.json
src/app/[lng]/(common)/InitClient.tsx
src/app/[lng]/(write)/write/page.tsx
src/app/components/organisms/Modal/Modal.stories.tsx
src/app/components/organisms/Modal/Modal.tsx
src/app/components/organisms/Modal/index.ts
src/utils/useModal.ts
tailwind.config.ts
yarn.lock

Toss-overlay를 활용하되 간편히 사용할 수 있도록 wrapper를 만들었습니다.
모달은 형태가 다양해질 수 있기에 compound component로 작업했습니다.
Q. 모달에도 바텀시트처럼 slide-up 애니메이션이 들어가야할까요? 영상에는 넣었지만 현재 코드에선 뺐습니다.
Example with Storybook
```
const Template: StoryFn<typeof Modal> = (args) => {
const modal = useModal();
return (
<Button
onClick={() =>
modal.open(
<Modal {...args}>
<Modal.Title>Modal Title</Modal.Title>
<Modal.ButtonContainer>
<Modal.Button variant={'outlined'}>Cancel</Modal.Button>
<Modal.Button variant={'contained'} onClick={() => {}}>
Confirm
</Modal.Button>
</Modal.ButtonContainer>
</Modal>,
)
}
>
<p>Show modal</p>
</Button>
);
};
const SimpleTemplate: StoryFn<typeof Modal> = (args) => (
<Modal {...args} title={'Modal Title'} text={'Modal Text'}>
<Modal.ButtonContainer>
<Modal.Button variant={'contained'} onClick={() => …
```

344 feature new modal system
